name: $(Build.DefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:rr)
variables:
  CertifiedServiceNameSeparated: [ServiceNameSeparated]
  CertifiedServiceName: [ServiceName]
  CertifiedServicePath: Services/$(CertifiedServiceName)
  CertifiedServiceVersion: [Version]
  CertifiedServiceVersionPath: [VersionString]
  ExtensionRevision: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  VstsFeed: 'CloudCompetenceCenter/Repsol-CloudCompetenceCenter-Packages'
  PodIdentitySelector: ccc-aks-orch-pod-$(Podsuffix)
  AzVersion: 4.5.0
resources:
  repositories:
    - repository: main
      type: git
      name: CloudCompetenceCenter
trigger:
  branches:
    include:
      - master
      - [ServiceName]*
  paths:
    include:
      - Services/[ServiceName]/[Version]
stages:
  - stage: Build
    jobs:
      - job: BuildNuget
        pool:
          name: CCC
        displayName: Build and Publish Nuget artifacts
        workspace:
          clean: all
        steps:
          - template: /CI/Templates/CCC-Apification-ContainerImage-Build.yaml

  - stage: EngDeploy
    displayName: "Eng Container Image"
    variables:
      - group: "MarketPlacePublish (Global)"
      - group: "Management (Eng)"
      - group: "MarketPlacePublish (Engineering)"
      - name: ExtensionVersionMajor
        value: "1"
      - name: Suffix
        value: eng
      - name: Podsuffix
        value: eng
      - name: PublishExtensionIdService
        value: "RepsolCCCExtension$(CertifiedServiceName)Eng"
      - name: PublishExtensionNameService
        value: "Repsol CCC VSTS $(CertifiedServiceNameSeparated) Extension (Engineering)"
    jobs:
      - deployment: ContainerImage
        displayName: "Container Image Docker Build"
        environment: Eng
        workspace:
          clean: all
        pool:
          name: RDT Repsol Linux EU
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /CI/Templates/CCC-Apification-ContainerImage-DockerBuild.yaml
      - deployment: ContainerImageApply
        displayName: "Container Image Apply"
        environment: Eng
        dependsOn: ContainerImage
        pool:
          name: CCC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /CI/Templates/CCC-Apification-ContainerImage-Apply.yaml
  - stage: AccDeploy
    displayName: "Acc Container Image"
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    variables:
      - group: "MarketPlacePublish (Global)"
      - group: "Management (DTAP-Aceptance)"
      - group: "MarketPlacePublish (LDTAP-Acceptance)"
      - name: ExtensionVersionMajor
        value: "1"
      - name: Suffix
        value: acc
      - name: Podsuffix
        value: acc
      - name: PublishExtensionIdService
        value: "RepsolCCCExtension$(CertifiedServiceName)Acc"
      - name: PublishExtensionNameService
        value: "Repsol CCC VSTS $(CertifiedServiceNameSeparated) Extension (Acceptance)"
    jobs:
      - deployment: ContainerImage
        displayName: "Container Image Deployment"
        environment: Acc
        workspace:
          clean: all
        pool:
          name: RDT Repsol Linux EU
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /CI/Templates/CCC-Apification-ContainerImage-Deployment.yaml
      - deployment: ContainerImageApply
        displayName: "Container Image Apply"
        environment: Acc
        dependsOn: ContainerImage
        pool:
          name: CCC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /CI/Templates/CCC-Apification-ContainerImage-Apply.yaml

  - stage: LDTAPDeploy
    displayName: "LDTAP Container Image"
    dependsOn: AccDeploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    variables:
      - group: "MarketPlacePublish (Global)"
      - group: "Management (DTAP)"
      - group: "MarketPlacePublish (DTAP)"
      - name: ExtensionVersionMajor
        value: "1"
      - name: Suffix
        value: ldtap
      - name: Podsuffix
        value: ldtap
      - name: PublishExtensionIdService
        value: "RepsolCCCExtension$(CertifiedServiceName)"
      - name: PublishExtensionNameService
        value: "Repsol CCC VSTS $(CertifiedServiceNameSeparated) Extension"
    jobs:
      - deployment: ContainerImage
        displayName: "Container Image Docker Build"
        environment: LDTAP
        workspace:
          clean: all
        pool:
          name: RDT Repsol Linux EU
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /CI/Templates/CCC-Apification-ContainerImage-DockerBuild.yaml
      - deployment: ContainerImageApply
        displayName: "Container Image Apply"
        environment: LDTAP
        dependsOn: ContainerImage
        pool:
          name: CCC
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /CI/Templates/CCC-Apification-ContainerImage-Apply.yaml
