name: $(Build.DefinitionName)-$(SourceBranchName)-$(Date:yyyyMMdd).$(Rev:rr)
variables:
  CertifiedServiceNameSeparated: [ServiceNameSeparated]
  CertifiedServiceName: [ServiceName]
  CertifiedServicePath: Services/$(CertifiedServiceName)
  CertifiedServiceVersion: [Version]
  CertifiedServiceVersionPath: [VersionString]
  ExtensionRevision: $[counter(format('{0:yyyyMMdd}', pipeline.startTime), 1)]
  VstsFeed: 'CloudCompetenceCenter/Repsol-CloudCompetenceCenter-Packages'
  PodIdentitySelector: ccc-aks-orch-pod-$(Podsuffix)
resources:
  repositories:
    - repository: main
      type: git
      name: CloudCompetenceCenter
trigger:
  branches:
    include:
      - master
      - [ServiceName]*
  paths:
    include:
      - Services/[ServiceName]/[Version]
stages:
  - stage: Build
    jobs:
      - job: BuildNuget
        pool:
          name: CCC
        displayName: Build and Publish Nuget artifacts
        workspace:
          clean: all
        steps:
          - template: /CI/Templates/CCC-Apification-ContainerImage-Build.yaml

  - stage: EngDeploy
    variables:
      - group: "MarketPlacePublish (Global)"
      - group: "Management (Eng)"
      - group: "MarketPlacePublish (Engineering)"
      - name: ExtensionVersionMajor
        value: 1
      - name: Suffix
        value: eng
      - name: Podsuffix
        value: eng
      - name: PublishExtensionIdService
        value: "RepsolCCCExtension$(CertifiedServiceName)Eng"
      - name: PublishExtensionNameService
        value: "Repsol CCC VSTS $(CertifiedServiceNameSeparated) Extension (Engineering)"
    displayName: "Eng Deployment"
    dependsOn: Build
    jobs:
      - deployment: ContainerImage
        displayName: "Container Image Deployment"
        environment: Eng
        pool:
          vmImage: ubuntu-16.04
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /CI/Templates/CCC-Apification-ContainerImage-Deployment.yaml

      - deployment: AllVersionsExtension
        displayName: "All Versions Extension Deployment"
        # dependsOn: ContainerImage
        environment: Eng
        workspace:
          clean: all
        pool:
          name: CCC
          # vmImage: windows-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../extension-pipeline.yaml
                  parameters:
                    ArtifactWithLatestsVersion: [ServiceName][Version]

  - stage: AccDeploy
    variables:
      - group: "MarketPlacePublish (Global)"
      - group: "Management (DTAP-Aceptance)"
      - group: "MarketPlacePublish (LDTAP-Acceptance)"
      - name: ExtensionVersionMajor
        value: 1
      - name: Suffix
        value: acc
      - name: Podsuffix
        value: acc
      - name: PublishExtensionIdService
        value: "RepsolCCCExtension$(CertifiedServiceName)Acc"
      - name: PublishExtensionNameService
        value: "Repsol CCC VSTS $(CertifiedServiceNameSeparated) Extension (Acceptance)"
    displayName: "Acc Deployment"
    dependsOn: Build
    jobs:
      - deployment: ContainerImage
        displayName: "Container Image Deployment"
        environment: Acc
        pool:
          vmImage: ubuntu-16.04
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /CI/Templates/CCC-Apification-ContainerImage-Deployment.yaml

      - deployment: AllVersionsExtension
        displayName: "All Versions Extension Deployment"
        dependsOn: ContainerImage
        environment: Acc
        workspace:
          clean: all
        pool:
          name: CCC
          # vmImage: windows-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../extension-pipeline.yaml
                  parameters:
                    ArtifactWithLatestsVersion: [ServiceName][Version]

  - stage: LDTAPDeploy
    variables:
      - group: "MarketPlacePublish (Global)"
      - group: "Management (DTAP)"
      - group: "MarketPlacePublish (DTAP)"
      - name: ExtensionVersionMajor
        value: 1
      - name: Suffix
        value:
      - name: Podsuffix
        value: ldtap
      - name: PublishExtensionIdService
        value: "RepsolCCCExtension$(CertifiedServiceName)"
      - name: PublishExtensionNameService
        value: "Repsol CCC VSTS $(CertifiedServiceNameSeparated) Extension"
    displayName: "LDTAP Deployment"
    dependsOn: AccDeploy
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    jobs:
      - deployment: ContainerImage
        displayName: "Container Image Deployment"
        environment: LDTAP
        pool:
          vmImage: ubuntu-16.04
        strategy:
          runOnce:
            deploy:
              steps:
                - template: /CI/Templates/CCC-Apification-ContainerImage-Deployment.yaml

      - deployment: AllVersionsExtension
        displayName: "All Versions Extension Deployment"
        dependsOn: ContainerImage
        environment: LDTAP
        workspace:
          clean: all
        pool:
          name: CCC
          # vmImage: windows-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - template: ../extension-pipeline.yaml
                  parameters:
                    ArtifactWithLatestsVersion: [ServiceName][Version]