#
# Module manifest for module 'CCC.[ServiceName].Common'
#
# Generated by: Repsol CCC Features Team
#
# Generated on: 07/05/2020

@{
    # Script module or binary module file associated with this manifest.
    RootModule    = ''

    # Version number of this module.
    ModuleVersion = '[version]'

    # Supported PSEditions
    # CompatiblePSEditions = @()

    # ID used to uniquely identify this module
    GUID          = '[NewGUID]'

    # Author of this module
    Author        = 'Repsol CCC'

    # Company or vendor of this module
    CompanyName   = 'Repsol'

    # Copyright statement for this module
    Copyright     = '(c) 2020 Repsol. All rights reserved.'

    # Description of the functionality provided by this module
    Description   = 'Scripts and templates for common use and referenced
        from the Repsol Cloud Competence Center developments
        related to the [ServiceName] Service'
    # Type files (.ps1xml) to be loaded when importing this module
    #    TypesToProcess    = @('src\types.ps1xml',
    #       'src\buildDefinitions.ps1xml')

    # Format files (.ps1xml) to be loaded when importing this module
    #    FormatsToProcess  = @('src\Approvals.format.ps1xml',
    #       'src\buildDefinitions.format.ps1xml',
    #       'src\TeamTypes.format.ps1xml',
    #       'src\builds.format.ps1xml',
    #       'src\team.format.ps1xml')

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @('CCC.[ServiceName].Common.psm1')

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    #FunctionsToExport = @()

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    # CmdletsToExport = @()

    # Variables to export from this module
    #VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    #AliasesToExport   = '*'

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData   = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @( '[ServiceName]', 'Repsol', 'CCC', 'VSTS', 'TFS', 'DevOps', 'VisualStudio', 'TeamServices')

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            # ProjectUri = 'https://github.com/DarqueWarrior/team'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''
}