# This workflow will do a clean install of node dependencies, build the source code, bundle the extension, create a release and upload the bundle as an asset to the release.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: VSCode Extension Bundle
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to apply'
        required: true
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm install -g vsce
    - run: vsce package
    - name: Inject slug/short variables # Add to the action variables with information as branch name
      uses: rlespinasse/github-slug-action@2.0.0
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.GITHUB_HEAD_REF_SLUG }}${{ github.event.inputs.tag }}
        body_path: LATEST_CHANGELOG.md
        release_name: Release ${{ env.GITHUB_HEAD_REF_SLUG }}${{ github.event.inputs.tag }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset
      if: github.event.inputs.tag == false
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`.
        asset_path: /home/runner/work/cccfeaturesutils/cccfeaturesutils/cccfeaturesutils-${{ env.GITHUB_HEAD_REF_SLUG }}.vsix
        asset_name: cccfeaturesutils-${{ env.GITHUB_HEAD_REF_SLUG }}.vsix
        asset_content_type: application/zip
